# The MQL file path
steps:
  - conf/step.yaml

inputs:
  ratings:
    file:
      path: examples/file_inputs
      format: csv
      options:
        nullValue: "空值"

showPreviewLines: 10

showQuery: true

cacheOnPreview: true

variables:
  myFavoriteMovie: '1260759144'

logLevel: INFO

output:
  file:
    dir: examples/file_outputs/op1