# The MQL file path
steps:
  - conf/step.yaml

inputs:
  ratings:
    file:
      path: examples/file_inputs
      format: csv
      options:
        delimiter: "\u0001"
        nullValue: "空值"

showPreviewLines: 10

showQuery: true

cacheOnPreview: true