steps:
  - examples/hive/step.yaml

inputs:
  tb1:
    hive:
      #非必须，默认值是default
      dbName: cdp_dw
      #必选值
      tbName: fact_campaign
      #非必选值，默认值是 1 = 1
      condition: etl_date='20220113'
      #非必选值：默认值是*
      columns: campaign_name,campaign_id

showPreviewLines: 10

showQuery: true

appName: MuziminSpark_Hive

output:
  hive:
    dbName: test_cdp_ods
    tbName: test_muzimin_spark
    tbType: full

outputs:
  out_tb1:
    hive:
      dbName: test_cdp_ods
      tbName: test_muzimin_spark_01
      tbType: dynamic
  out_tb2:
    hive:
      dbName: test_cdp_ods
      tbName: test_muzimin_spark_02
      tbType: static