steps:
  - examples/hive/step.yaml

inputs:
  tb1:
    hive:
      dbName: cdp_dw
      tbName: fact_campaign
      condition: etl_date='20220113'

showPreviewLines: 10

showQuery: true

appName: MuziminSpark_Hive

output:
  hive:
    dbName: test_cdp_ods
    tbName: test_muzimin_spark
    tbType: full

outputs:
  out_tb1:
    hive:
      dbName: test_cdp_ods
      tbName: test_muzimin_spark_01
      tbType: dynamic
  out_tb2:
    hive:
      dbName: test_cdp_ods
      tbName: test_muzimin_spark_02
      tbType: static